//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meth_Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCours
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public int YearDegreeID { get; set; }
        public string FinalDegree { get; set; }
        public bool IsFinished { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual YearDegree YearDegree { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
